### ISSUE TITLE
live example error in IE 11

### ISSUE THREAD

**Issue by cs09g** [foo123/FILTER.js#10]
exmaple: http://foo123.github.io/examples/filter/

in IE11, doesn't show any images so I looked development tools then it shows "SCRIPT1046" error

**Comment by foo123** [comment]
Let me take a look and get back at you. This is a new update.

**Comment by foo123** [comment]
Yes i got it, it is a typo. i'll update the repository soon with other changes as well Check back later

**Comment by foo123** [comment]
Fixed the IE typo, plus some extra updates. Get the updated 0.9.0 tagged version and make sure to refresh your browser when viewing the live examples.

**Comment by cs09g** [comment]
one more thing. Apply button is under the 'synchronouse / parallel' div so there is little space to click the button. suggest you to set width on 'synchronouse / parallel' div
