### ISSUE TITLE
HAAR data generation

### ISSUE THREAD

**Issue by Rouche** [foo123/FILTER.js#11]
Hello, this repo seems still alive, so i take my chance!

I am trying to find a way to generate HAAR data from https://github.com/opencv/opencv/tree/master/data/haarcascades (I need haarcascade_upperbody.xml) so we can detect if its a valid ID photo.
Did you used the haartojs.php from HAAR.js?

I was wondering if your version of HaarDetection will work with data in master of opencv (v3.2.0 now).

~~Also, i need to use lowest javascript files as possible.~~ Thats nice, custom build will do the trick!

Thanks a lot.

**Comment by foo123** [comment]
Yes use the conversion tools from the HAAR.js repo (**note:** json conversion seems to have an issue, but js conversion works fine), haar cacsades in this repo (FILTER.js) use exactly same format as those in HAAR.js repo.

**Comment by Rouche** [comment]
Thanks for the answer.
