### ISSUE TITLE
Is it possible to use filter codecs to decode a grayscale image matrix

### ISSUE THREAD

**Issue by danielyaa5** [foo123/FILTER.js#5]
I have a matrix of values from 0 to 255 representing a grayscale image. I would like to display this image on the web, would filter.js be able to help me do that?

**Comment by foo123** [comment]
hmm can you provide an example and see how it can help

**Comment by danielyaa5** [comment]
Like an example of the matrix data?

Really appreciate the help.

Daniel Yakobian - djy18@case.edu
Case Western Reserve University - 2016
Treasurer - The International and Multicultural Exchange Society
Android Developer - The MetroHealth System

**Comment by foo123** [comment]
Yes, an example code of your matrxi data and how you want them saved, so i can suggest sth specific
