### ISSUE TITLE
Use filters on live video webcam feed

### ISSUE THREAD

**Issue by hezhez** [foo123/FILTER.js#6]
Hi !

Is it possible to apply (Or preview before applying) filters on webcam live feed like the video example ?

The feed tag looks like this:

<video id="video" src="blob:http%3A//website.net/14635dfa-a265-4b02-be7d-e7a68e802795" width="960" height="720"></video>

**Comment by foo123** [comment]
Yes it should be possible using WebRTC technology (with browsers which support it) and changing the filter-video example to use the webcam instead of the video

**Comment by hezhez** [comment]
Thanks alot !
one more question, the example and the api refference is not so clear about the video, can you please attach or write here about the right method to do it (only for the video) ?

**Comment by foo123** [comment]
hmm i havent used an example with webcam, but it should be easy to adapt the video example for webcam.

What the example does is read a video frame (on `requestAnimationFrame`) and draw it on a canvas (actually a `FILTER.Image`, which uses canvas underneath), then any filters can be applied there, that's all in a nutshell, if you have a specific question, open another issue and see if i can help, cheers
