### ISSUE TITLE
Video tag from webcam is not converting into canvas

### ISSUE THREAD

**Issue by hezhez** [foo123/FILTER.js#7]
Hi,

i have this tag - 
```html
<video id="video" src="blob:http%3A//website.net/ac025a13-f2cc-4994-88c4-5d24013df611" width="960" height="720"></video>
```

when i'm calling the `FILTER.HTMLImageLoader.load([videotagid])` i get an data error.

i can't manage to transform the webcam video tag into live canvas which on it i can put live filters like the example.

I appreciate all you help.

**Comment by foo123** [comment]
first try this to kake `video` tag more compatible:

```html
<!-- autoplay -->
 <video id="video" loop="true" controls="true">
 <source src=blob:http%3A//website.net/ac025a13-f2cc-4994-88c4-5d24013df611" type="video/mp4">
 Video is not supported
 </video>
```

Then capure th video into a `FILTER.Image` like the following:

```javascript
var video = document.getElementById('video');
var videoFrame = FILTER.Image().restorable(false);
// add the videoFrame on page
document.getElementById('container').appendChild(videoFrame.domElement);
 // start process when the video is playing
video,addEventListener("play", processVideo, false );
function processVideo()
{
      // draw current video frame
      videoFrame.setImage( video );
      videoFrame.apply( my_awesome_filter ); 
       // Render every fixed interval
      requestAnimationFrame( processVideo );
}
```

Something liek this should work with webcam as well, if change the video to a webcam

**Comment by hezhez** [comment]
Thanks, but it is not working.

By the way, i managed to get webcam stream into canvas, but  i think there is a bug accessing canvas directly from FILTER.image().

When i'm trying to access canvas directly like this - 
var c = document.getElementById('canvas');
var videoFrame = FILTER.Image(c).restorable( false );

I get data error.. any solutions ?

**Comment by foo123** [comment]
You will have to post your whole sample code (at least all the relevant parts) and exactly what error you get, or create a jsfiddle if possible

**Comment by foo123** [comment]
It is possible you are trying to read the image (or save canvas to `FILTER.Image`) before data (rom webcam) are actually ready. Try putting a small delay and/or add an event on data ready

**Comment by hezhez** [comment]
Sorry for the late response, got it to work.
I needed to bind the filter apply to click event.

Thanks for your kind help.
